server:
  port: 0
  error:
    include-message: always
  servlet:
    context-path: /api/v1

spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Europe/Moscow
  web:
    locale: en_US
  cloud:
    loadbalancer:
      cache:
        enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}

root:
  username: root
  password: toor

token:
  expire: 3600

test:
  value: HelloWorld


subscribe-topic: /topic/requests
destination-topic: /queue/responses
ws-server: ${WS_SERVER_URL:ws://localhost:9898/movieswipper-ws}
