server:
  port: 0
  error:
    include-message: always

spring:
  webflux:
    base-path: /api/v1
  r2dbc:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jackson:
    time-zone: Europe/Moscow
  web:
    locale: en_US
  cloud:
    loadbalancer:
      cache:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}



logging:
  level:
    org.springframework.data.r2dbc: debug
